// apps/plant-app/src/components/forms/forms-components/TextInput.tsx
import React from 'react';

interface TextInputProps {
  id: string;
  label: string;
  type?: 'text' | 'password' | 'email' | 'number' | 'tel' | 'url'; // Extendable to other types as needed
  value: string;
  onChange: React.ChangeEventHandler<HTMLInputElement>;
  required?: boolean;
  placeholder?: string;
  error?: string;
}

const TextInput: React.FC<TextInputProps> = ({
  id,
  label,
  type = 'text',
  value,
  onChange,
  required = false,
  placeholder = '',
  error,
}) => (
  <div className="mb-4">
    <label htmlFor={id} className="block text-sm font-bold mb-2">
      {label}
    </label>
    <input
      id={id}
      type={type}
      value={value}
      onChange={onChange}
      required={required}
      placeholder={placeholder}
      className={`shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline ${
        error ? 'border-red-500' : ''
      }`}
    />
    {error && <p className="text-red-500 text-xs italic">{error}</p>}
  </div>
);

export default TextInput;

// apps/verdiApp/src/components/forms/TextInput.vue
<template>
  <div class="mb-4 w-full">
    <label :for="id" class="block text-carob text-sm font-bold mb-2">
      {{ label }}:
    </label>
    <input
      :type="type"
      :id="id"
      :value="modelValue"
      :required="required"
      :placeholder="placeholder"
      class="shadow appearance-none border border-pistache rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
    />
    <p v-if="errorMessage" class="text-red-500 text-xs italic">
      {{ errorMessage }}
    </p>
  </div>
</template>

<script>
export default {
  name: 'TextInput',
  props: {
    id: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
    },
    modelValue: {
      type: String,
      required: true,
    },
    required: {
      type: Boolean,
      default: false,
    },
    placeholder: {
      type: String,
      default: '',
    },
    errorMessage: {
      type: String,
      default: '',
    },
    type: {
      type: String,
      default: 'text',
    },
  },
  emits: ['update:modelValue'],
  watch: {
    modelValue(newVal) {
      this.$emit('update:modelValue', newVal);
    },
  },
};
</script>
